insert into products (product_code, product_count, product_size, product_name) values ('ID-SN', 21, 1, 'Bread - Ciabatta Buns');
insert into products (product_code, product_count, product_size, product_name) values ('IN-UL', 27, 2, 'Wine - Soave Folonari');
insert into products (product_code, product_count, product_size, product_name) values ('ID-NT', 7, 3, 'Veal - Inside, Choice');
insert into products (product_code, product_count, product_size, product_name) values ('US-SC', 12, 4, 'Salt - Seasoned');
insert into products (product_code, product_count, product_size, product_name) values ('CN-22', 24, 5, 'Teriyaki Sauce');
insert into products (product_code, product_count, product_size, product_name) values ('PG-SAN', 39, 6, 'Wine - Beaujolais Villages');
insert into products (product_code, product_count, product_size, product_name) values ('LK-7', 17, 7, 'Juice - Clam, 46 Oz');
insert into products (product_code, product_count, product_size, product_name) values ('BO-B', 27, 8, 'Anisette - Mcguiness');
insert into products (product_code, product_count, product_size, product_name) values ('US-FL', 18, 9, 'Duck - Breast');
insert into products (product_code, product_count, product_size, product_name) values ('TR-26', 41, 10, 'Coffee Decaf Colombian');
insert into products (product_code, product_count, product_size, product_name) values ('AU-NSW', 8, 11, 'Milk - Chocolate 250 Ml');
insert into products (product_code, product_count, product_size, product_name) values ('MY-02', 13, 12, 'Smoked Tongue');
insert into products (product_code, product_count, product_size, product_name) values ('CZ-ZL', 25, 13, 'Cookies - Oreo, 4 Pack');
insert into products (product_code, product_count, product_size, product_name) values ('BR-TO', 10, 14, 'Bread Base - Toscano');
insert into products (product_code, product_count, product_size, product_name) values ('GL-U-A', 20, 15, 'Red Currant Jelly');
insert into products (product_code, product_count, product_size, product_name) values ('SE-W', 8, 16, 'Spinach - Spinach Leaf');
insert into products (product_code, product_count, product_size, product_name) values ('NO-17', 22, 17, 'Syrup - Monin - Blue Curacao');
insert into products (product_code, product_count, product_size, product_name) values ('LK-7', 32, 18, 'Bread - Dark Rye, Loaf');
insert into products (product_code, product_count, product_size, product_name) values ('MM-17', 6, 19, 'Skewers - Bamboo');
insert into products (product_code, product_count, product_size, product_name) values ('TZ-26', 7, 20, 'Barramundi');
insert into products (product_code, product_count, product_size, product_name) values ('US-AK', 4, 21, 'Soup - Knorr, French Onion');
insert into products (product_code, product_count, product_size, product_name) values ('US-NM', 29, 22, 'Flour - Strong');
insert into products (product_code, product_count, product_size, product_name) values ('PH-DAO', 32, 23, 'Beer - Moosehead');
insert into products (product_code, product_count, product_size, product_name) values ('US-WY', 25, 24, 'Mop Head - Cotton, 24 Oz');
insert into products (product_code, product_count, product_size, product_name) values ('PG-NSB', 36, 25, 'Beef - Ground Medium');
insert into products (product_code, product_count, product_size, product_name) values ('JP-47', 28, 26, 'Kellogs All Bran Bars');
insert into products (product_code, product_count, product_size, product_name) values ('US-AK', 8, 27, 'Soup - Knorr, Country Bean');
insert into products (product_code, product_count, product_size, product_name) values ('US-WA', 41, 28, 'Yogurt - Blueberry, 175 Gr');
insert into products (product_code, product_count, product_size, product_name) values ('MY-13', 19, 29, 'Fudge - Chocolate Fudge');
insert into products (product_code, product_count, product_size, product_name) values ('TT-WTO', 31, 30, 'Fish - Atlantic Salmon, Cold');
insert into products (product_code, product_count, product_size, product_name) values ('IN-LD', 35, 31, 'Parsley Italian - Fresh');
insert into products (product_code, product_count, product_size, product_name) values ('ID-RI', 32, 32, 'Lamb - Whole Head Off');
insert into products (product_code, product_count, product_size, product_name) values ('MG-T', 14, 33, 'Stainless Steel Cleaner Vision');
insert into products (product_code, product_count, product_size, product_name) values ('CO-MET', 30, 34, 'Roe - Lump Fish, Red');
insert into products (product_code, product_count, product_size, product_name) values ('CA-MB', 41, 35, 'Dr. Pepper - 355ml');
insert into products (product_code, product_count, product_size, product_name) values ('US-WA', 1, 36, 'Beer - True North Lager');
insert into products (product_code, product_count, product_size, product_name) values ('ID-JT', 6, 37, 'Cheese - Brie, Cups 125g');
insert into products (product_code, product_count, product_size, product_name) values ('CA-MB', 40, 38, 'Lettuce - Curly Endive');
insert into products (product_code, product_count, product_size, product_name) values ('PY-19', 14, 39, 'Sauce - Cranberry');
insert into products (product_code, product_count, product_size, product_name) values ('CA-ON', 8, 40, 'Wine - Chateauneuf Du Pape');
insert into products (product_code, product_count, product_size, product_name) values ('AU-NT', 31, 41, 'Wine - Jafflin Bourgongone');
insert into products (product_code, product_count, product_size, product_name) values ('DZ-33', 41, 42, 'Tart Shells - Sweet, 3');
insert into products (product_code, product_count, product_size, product_name) values ('IR-23', 18, 43, 'Swiss Chard - Red');
insert into products (product_code, product_count, product_size, product_name) values ('MW-KR', 28, 44, 'Squid Ink');
insert into products (product_code, product_count, product_size, product_name) values ('AU-NSW', 15, 45, 'Nut - Pecan, Halves');
insert into products (product_code, product_count, product_size, product_name) values ('BD-3', 16, 46, 'Cheese - Taleggio D.o.p.');
insert into products (product_code, product_count, product_size, product_name) values ('US-MT', 13, 47, 'Mcguinness - Blue Curacao');
insert into products (product_code, product_count, product_size, product_name) values ('AU-QLD', 28, 48, 'Beans - Yellow');
insert into products (product_code, product_count, product_size, product_name) values ('MM-05', 18, 49, 'Oil - Hazelnut');
insert into products (product_code, product_count, product_size, product_name) values ('US-CA', 4, 50, 'Browning Caramel Glace');
insert into products (product_code, product_count, product_size, product_name) values ('IT-34', 18, 51, 'Wine - Casillero Deldiablo');
insert into products (product_code, product_count, product_size, product_name) values ('CO-ANT', 42, 52, 'Cinnamon Buns Sticky');
insert into products (product_code, product_count, product_size, product_name) values ('CN-42', 18, 53, 'Sprite, Diet - 355ml');
insert into products (product_code, product_count, product_size, product_name) values ('US-ME', 14, 54, 'Bread - English Muffin');
insert into products (product_code, product_count, product_size, product_name) values ('PG-MPM', 36, 55, 'Soup - Tomato Mush. Florentine');
insert into products (product_code, product_count, product_size, product_name) values ('GH-BA', 2, 56, 'Cookie Choc');
insert into products (product_code, product_count, product_size, product_name) values ('GB-ENG', 20, 57, 'Tea - Green');
insert into products (product_code, product_count, product_size, product_name) values ('CA-BC', 15, 58, 'Sugar - Splenda Sweetener');
insert into products (product_code, product_count, product_size, product_name) values ('US-AL', 15, 59, 'Pepper - Chillies, Crushed');
insert into products (product_code, product_count, product_size, product_name) values ('IN-MN', 4, 60, 'Scotch - Queen Anne');
insert into products (product_code, product_count, product_size, product_name) values ('AF-LOW', 32, 61, 'Pasta - Orecchiette');
insert into products (product_code, product_count, product_size, product_name) values ('BF-NAM', 37, 62, 'Liners - Baking Cups');
insert into products (product_code, product_count, product_size, product_name) values ('US-AK', 16, 63, 'Tomatoes - Vine Ripe, Yellow');
insert into products (product_code, product_count, product_size, product_name) values ('TH-63', 6, 64, 'Mussels - Cultivated');
insert into products (product_code, product_count, product_size, product_name) values ('ES-CT', 9, 65, 'Pepper - Chipotle, Canned');
insert into products (product_code, product_count, product_size, product_name) values ('AU-TAS', 18, 66, 'Bread - Olive Dinner Roll');
insert into products (product_code, product_count, product_size, product_name) values ('CV-S', 28, 67, 'Melon - Cantaloupe');
insert into products (product_code, product_count, product_size, product_name) values ('GR-71', 41, 68, 'Ham - Virginia');
insert into products (product_code, product_count, product_size, product_name) values ('RU-SA', 30, 69, 'Gin - Gilbeys London, Dry');
insert into products (product_code, product_count, product_size, product_name) values ('MO-U-A', 12, 70, 'Oil - Peanut');
insert into products (product_code, product_count, product_size, product_name) values ('US-TN', 4, 71, 'Cilantro / Coriander - Fresh');
insert into products (product_code, product_count, product_size, product_name) values ('BR-RS', 40, 72, 'Wine - Sawmill Creek Autumn');
insert into products (product_code, product_count, product_size, product_name) values ('US-OH', 2, 73, 'Pasta - Cheese / Spinach Bauletti');
insert into products (product_code, product_count, product_size, product_name) values ('MY-12', 1, 74, 'Dragon Fruit');
insert into products (product_code, product_count, product_size, product_name) values ('US-MA', 26, 75, 'Bread - Crumbs, Bulk');
insert into products (product_code, product_count, product_size, product_name) values ('US-SC', 25, 76, 'Beer - Moosehead');
insert into products (product_code, product_count, product_size, product_name) values ('CN-43', 9, 77, 'Wine - Alicanca Vinho Verde');
insert into products (product_code, product_count, product_size, product_name) values ('AU-VIC', 41, 78, 'Sponge Cake Mix - Vanilla');
insert into products (product_code, product_count, product_size, product_name) values ('VE-E', 30, 79, 'Wine - Red, Cabernet Merlot');
insert into products (product_code, product_count, product_size, product_name) values ('AU-QLD', 19, 80, 'Napkin White - Starched');
insert into products (product_code, product_count, product_size, product_name) values ('ML-1', 6, 81, 'Calypso - Lemonade');
insert into products (product_code, product_count, product_size, product_name) values ('SB-CE', 38, 82, 'Tea - Mint');
insert into products (product_code, product_count, product_size, product_name) values ('CI-10', 22, 83, 'Rosemary - Dry');
insert into products (product_code, product_count, product_size, product_name) values ('PH-BTN', 24, 84, 'Container - Foam Dixie 12 Oz');
insert into products (product_code, product_count, product_size, product_name) values ('CL-AI', 37, 85, 'Apple - Royal Gala');
insert into products (product_code, product_count, product_size, product_name) values ('LS-C', 16, 86, 'Lamb - Shoulder, Boneless');
insert into products (product_code, product_count, product_size, product_name) values ('CN-65', 31, 87, 'Wine - Chateau Bonnet');
insert into products (product_code, product_count, product_size, product_name) values ('ID-MU', 36, 88, 'Cheese - Comtomme');
insert into products (product_code, product_count, product_size, product_name) values ('US-MI', 41, 89, 'Beans - Kidney White');
insert into products (product_code, product_count, product_size, product_name) values ('PG-WPD', 31, 90, 'Wine - Chenin Blanc K.w.v.');
insert into products (product_code, product_count, product_size, product_name) values ('AU-QLD', 3, 91, 'Mushroom - White Button');
insert into products (product_code, product_count, product_size, product_name) values ('PL-MA', 2, 92, 'Cheese - Cambozola');
insert into products (product_code, product_count, product_size, product_name) values ('BR-BA', 21, 93, 'Chocolate - Milk');
insert into products (product_code, product_count, product_size, product_name) values ('BR-RO', 39, 94, 'Bread - White, Unsliced');
insert into products (product_code, product_count, product_size, product_name) values ('US-IA', 18, 95, 'Bread Foccacia Whole');
insert into products (product_code, product_count, product_size, product_name) values ('AU-NSW', 21, 96, 'Bagel - Ched Chs Presliced');
insert into products (product_code, product_count, product_size, product_name) values ('SB-ML', 35, 97, 'Chickensplit Half');
insert into products (product_code, product_count, product_size, product_name) values ('PG-EPW', 31, 98, 'Wine - Vidal Icewine Magnotta');
insert into products (product_code, product_count, product_size, product_name) values ('CG-8', 41, 99, 'Nut - Pumpkin Seeds');
insert into products (product_code, product_count, product_size, product_name) values ('PG-WBK', 32, 100, 'Rum - Cream, Amarula');

insert into storages (storage_aviable, storage_name) values (true, '494379200-6');
insert into storages (storage_aviable, storage_name) values (true, '170310587-7');
insert into storages (storage_aviable, storage_name) values (false, '632357954-5');
insert into storages (storage_aviable, storage_name) values (false, '547535955-5');
insert into storages (storage_aviable, storage_name) values (false, '923003689-7');
insert into storages (storage_aviable, storage_name) values (false, '385001763-X');
insert into storages (storage_aviable, storage_name) values (true, '033267235-2');
insert into storages (storage_aviable, storage_name) values (false, '857528281-6');
insert into storages (storage_aviable, storage_name) values (true, '064392445-0');
insert into storages (storage_aviable, storage_name) values (false, '660190112-1');
insert into storages (storage_aviable, storage_name) values (false, '456254558-5');
insert into storages (storage_aviable, storage_name) values (false, '768650475-1');
insert into storages (storage_aviable, storage_name) values (true, '478295741-6');
insert into storages (storage_aviable, storage_name) values (false, '136541009-9');
insert into storages (storage_aviable, storage_name) values (false, '332182828-6');
